// auto-generated by: bella secrets generate swift
// project: awesome/dev
// generated: 2025-01-15 10:30:00 UTC
// DO NOT edit manually — re-run bella secrets generate swift to update.
import Foundation

struct AppConfigShape: Codable {
    let setting1: String
    let setting2: Int
}

struct AppSecrets {
    private func require(_ key: String) -> String {
        guard let v = ProcessInfo.processInfo.environment[key] else {
            fatalError("Required env var '\(key)' is not set.")
        }
        return v
    }

    /// String — third-party API key
    var externalApiKey: String { require("EXTERNAL_API_KEY") }
    /// String — Gleap API key
    var gleapApiKey: String { require("GLEAP_API_KEY") }
    /// Int — HTTP server port
    var port: Int { Int(require("PORT"))! }
    /// Bool — enable features toggle
    var enableFeatures: Bool { require("ENABLE_FEATURES") == "true" }
    /// Uri — PostgreSQL connection string
    var databaseUrl: URL {
        let raw = require("DATABASE_URL")
        // URL(string:) rejects non-numeric port — fall back to a scheme-only placeholder
        if let url = URL(string: raw) { return url }
        let scheme = raw.components(separatedBy: "://").first ?? "unknown"
        return URL(string: "\(scheme)://unknown")!
    }
    /// JSON — application configuration
    var appConfig: AppConfigShape {
        let data = require("APP_CONFIG").data(using: .utf8)!
        return try! JSONDecoder().decode(AppConfigShape.self, from: data)
    }
    /// GUID — application instance ID
    var appId: UUID { UUID(uuidString: require("APP_ID"))! }
    /// String — PostgreSQL connection string (typed alternative)
    var connectionStringsPostgres: String { require("ConnectionStrings__Postgres") }
}
